# This workflow will generate and update the lists in the 'lists' branch each night at 0 UTC

name: Generate OFAC sanctioned digital currency addresses lists each night at 0 UTC

on:
  schedule:
    - cron: '24 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-lists:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Download the sdn_advanced.xml file
      run: |
        wget https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/SDN_ADVANCED.ZIP
        unzip SDN_ADVANCED.ZIP
        ls -l
    - name: Generate TXT and JSON files for all assets
      run: |
        mkdir data
        python3 generate-address-list.py XBT ETH XMR LTC ZEC DASH BTG ETC BSV BCH XVG USDC USDT XRP TRX ARB BSC -f JSON TXT -path ./data -sdn SDN_ADVANCED.XML
    - name: Create and switch to lists branch
      run: |
        git config --local user.email "45324+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git fetch origin lists:lists || git checkout -b lists
        git checkout lists
    - name: Update files and commit
      run: |
        cp data/* .
        git add sanctioned_addresses_* -f
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Automatically updated lists: $(date)"
          git push origin lists
        fi
